spring:
  aop:
    proxy-target-class: true

server:
  port: 8443
  session:
    cookie:
      name: websessionid
    timeout: 600
  ssl:
      key-alias: webserver
      key-store: webserverkeystore.jks
      key-store-password: bhAEyEdlssVWxemQ4VzMkgOEPvCdApUTzrkTHKpH
      key-password: bhAEyEdlssVWxemQ4VzMkgOEPvCdApUTzrkTHKpH

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: https://localhost:8444/uaa/oauth/token
      userAuthorizationUri: https://localhost:8444/uaa/oauth/authorize
      clientId: gateway
      clientSecret: Hqta28Ns4SOTnbg2Iqmh7RQSYYYfV60X6adkGoq1
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzbfcUImbbrJ4/S4OYc6k
          bq/LdoK7GOdXQLSBXfcVcsMHo8Wy2u3Sdp9jDOf4JQQAOEKmw/Nrev386GTIRPIi
          AxjYmfNYPGyqPrAUmWUjjZVN1Khd24Cdj3o3ARqyJCWM8hxFX5siYJcX9yyQinTp
          b8OSco2t5u/aZSZKH++MUddpvL9vIerehq9rA7KJmjYG64R8p8wvERpfZXEIS1iW
          yAc048j57MV2BUs3JROGM2Wmvqq8AoEbjP/Qn/MDUkE2+9no5SUhlTUch/M5DtOV
          m7zhCxmW/y35wJBysgqyJy2VMfqzNSYSAzSVbtzQEZrZxIK5QwzW8fOWUdYqQVq3
          JwIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resource:
      path: /ca/**
      url: https://localhost:8445/
    user:
      path: /auth/**
      url: https://localhost:8444/uaa/user